#ifndef STATUS_H
#define STATUS_H

enum e_Emociones
{
    SORPRENDIDO=0,
    ENAMORADO,
    ASUSTADO,
    CANSADO,
    DESCANSANDO,
    ESCUCHANDO,
    FURIOSO,
    MOLESTO,
    MIEDO,
    ASQUEADO,
    CONFUNDIDO,
    INTERESADO,
    ABURRIDO,
    PODEROSO,
    PACIFICO,
    ANSIOSO,
    CULPABLE,
    CRITICO,
    SORPRENDIDO_NEGATIVO,
    SORPRENDIDO_POSITIVO,
    ENOJADO_NEGATIVO,
    ENOJADO_POSITIVO,
    FELIZ_NEGATIVO,
    FELIZ_POSITIVO,
    TRISTE_NEGATIVO,
    TRISTE_POSITIVO,
    HERIDO_NEGATIVO,
    HERIDO_POSITIVO,
    NEUTRO,
    HUMILLADO,
    RECHAZADO,
    CELOSO,
    ODIOSO,
    DESQUISIADO, 
    VENGATIVO,
    FRUSTRADO,
    DISTANTE
};

void actualizar_estado(void);

#endif